spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.mediconnect: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

file:
  upload-dir: ./uploads
  max-size: 10485760
  allowed-types: application/pdf,image/jpeg,image/png
  allowed-extensions: pdf,jpg,jpeg,png
