# Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# MongoDB Configuration (Atlas)
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mediconnect}
      database: mediconnect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Performance Configuration
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    enabled: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  access-token-expiration: 300000
  refresh-token-expiration: 600000

# AWS S3 Configuration
aws:
  s3:
    bucket: ${S3_BUCKET_NAME:mediconnect-files}
  region: ${AWS_REGION:ap-south-1}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

# Logging Configuration
logging:
  level:
    root: INFO
    com.mediconnect: DEBUG
  file:
    name: logs/mediconnect.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# WebSocket Configuration
websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}

# Security Configuration
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when-authorized  # More secure
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
      show-values: when-authorized  # Hide sensitive values
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
    diskspace:
      enabled: true
      threshold: 10MB
    ping:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true