spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mediconnect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

jwt:
  secret: ''
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.mediconnect: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

file:
  upload-dir: ./uploads/doctor-documents
  max-size: 10485760 # 10MB in bytes
  allowed-types: application/pdf,image/jpeg,image/png
  allowed-extensions: pdf,jpg,jpeg,png

aws:
  s3:
    bucket: mediconnect-app
  accessKeyId: ''
  secretAccessKey: ''
  region: ap-south-1

google:
  maps:
    api:
      key: ''