[phases.setup]
nixPkgs = ["nodejs", "nodePackages.http-server"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "http-server build -p $PORT -a 0.0.0.0" 